httpProxy: "http://127.0.0.1:1087"

httpsProxy: "http://127.0.0.1:1087"

packageExtensions:
  "@cloudbase/cli@*":
    dependencies:
      xdg-basedir: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.js
